# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: docs

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

# trigger for all PRs and changes to main
on:
  push:
    branches:
      - main
  pull_request:

jobs:

  # test doc links still work
  docs:
    name: Rustdocs are clean
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ amd64 ]
        rust: [ nightly ]
    container:
      image: ${{ matrix.arch }}/rust
      env:
        RUSTDOCFLAGS: "-Dwarnings --enable-index-page -Zunstable-options"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install python dev
        run: |
          apt update
          apt install -y libpython3.11-dev
      - name: Setup Rust toolchain
        uses: ./.github/actions/setup-builder
        with:
          rust-version: ${{ matrix.rust }}
      - name: Run cargo doc
        run: cargo doc --document-private-items --no-deps --workspace --all-features
      - name: Fix file permissions
        shell: sh
        run: |
          chmod -c -R +rX "target/doc" |
          while read line; do
              echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          name: crate-docs
          path: target/doc

  deploy:
    # Only deploy if a push to main
    if: github.ref_name == 'main' && github.event_name == 'push'
    needs: docs
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download crate docs
        uses: actions/download-artifact@v5
        with:
          name: crate-docs
          path: website/build
      - name: Prepare website
        run: |
          tar -xf website/build/artifact.tar -C website/build
          rm website/build/artifact.tar
          cp .asf.yaml ./website/build/.asf.yaml
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        if: github.event_name == 'push' && github.ref_name == 'main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/build
          publish_branch: asf-site
          # Avoid accumulating history of in progress API jobs: https://github.com/apache/arrow-rs/issues/5908
          force_orphan: true
